create table if not exists public.devocionales (
  id bigint generated by default as identity primary key,
  titulo text not null,
  slug text not null unique,
  resumen text,
  contenido text not null,
  introduccion_html text,
  contenido_html text,
  versiculo text,
  categorias text[] not null default '{}',
  autora text not null default 'Equipo Mujeres con Propósito',
  imagen_url text,
  publicado boolean not null default false,
  fecha_publicacion timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.devocionales add column if not exists created_by uuid references auth.users(id) on delete set null default auth.uid();

create index if not exists devocionales_publicados_fecha_idx
on public.devocionales (publicado, fecha_publicacion desc);

alter table public.devocionales enable row level security;

create policy "public read published devocionales"
on public.devocionales for select to anon, authenticated
using (publicado = true and fecha_publicacion is not null and fecha_publicacion <= now());

create policy "authenticated write devocionales"
on public.devocionales for all to authenticated
using (public.current_user_role() = 'crud')
with check (public.current_user_role() = 'crud');
