-- Flujo editorial de revisión para devocionales: Editor prepara/edita,
-- Reviewer aprueba y publica. Nada que un Editor escriba llega al público
-- sin que un Reviewer lo apruebe explícitamente. Super Admin conserva su
-- CRUD directo sin cambios.

-- 1. Columnas nuevas -----------------------------------------------------
alter table public.devocionales
  alter column titulo drop not null,
  alter column contenido drop not null;

alter table public.devocionales
  add column if not exists estado text not null default 'borrador'
    check (estado in ('borrador','en_revision','cambios_solicitados')),
  add column if not exists pending_content jsonb,
  add column if not exists pending_fecha_publicacion timestamptz;

-- Sincroniza supabase-schema.sql: compartidos ya existía en producción
-- (migración 20260904090000) pero faltaba en el archivo maestro.
alter table public.devocionales add column if not exists compartidos integer not null default 0;

-- 2. Historial de auditoría ------------------------------------------------
create table if not exists public.devocional_historial (
  id bigint generated by default as identity primary key,
  devocional_id bigint references public.devocionales(id) on delete set null,
  devocional_titulo text,
  devocional_slug text,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text,
  accion text not null check (accion in (
    'creado', 'editado', 'enviado_a_revision', 'cambios_solicitados',
    'retirado', 'aprobado_publicado', 'despublicado', 'eliminado'
  )),
  nota text,
  created_at timestamptz not null default now()
);

create index if not exists devocional_historial_devocional_idx
on public.devocional_historial (devocional_id, created_at desc);

alter table public.devocional_historial enable row level security;

drop policy if exists "super admin read devocional historial" on public.devocional_historial;
create policy "super admin read devocional historial"
on public.devocional_historial for select to authenticated
using (public.is_super_admin());

drop policy if exists "reviewers read devocional historial" on public.devocional_historial;
create policy "reviewers read devocional historial"
on public.devocional_historial for select to authenticated
using (public.has_permission('reviewer'));

drop policy if exists "authors read own devocional historial" on public.devocional_historial;
create policy "authors read own devocional historial"
on public.devocional_historial for select to authenticated
using (
  public.has_permission('editor')
  and devocional_id is not null
  and exists (
    select 1 from public.devocionales d
    where d.id = devocional_historial.devocional_id and d.created_by = auth.uid()
  )
);
-- Sin política de insert/update/delete: solo lo escriben las funciones y
-- triggers security definer de esta migración.

-- 3. Trigger de protección de columnas en vivo ----------------------------
-- Bloquea que un UPDATE/INSERT ordinario (PATCH/POST vía PostgREST) de un
-- Editor o Reviewer toque columnas "en vivo" o de publicación. Solo se
-- exime si el actor es Super Admin, o si la propia función security
-- definer activó el flag transaccional de bypass antes de su UPDATE
-- interno (perform set_config('app.devocional_guard_bypass','on', true)).
create or replace function public.devocionales_guard_direct_writes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if public.is_super_admin() or current_setting('app.devocional_guard_bypass', true) = 'on' then
    return new;
  end if;

  if TG_OP = 'INSERT' then
    if new.titulo is not null or new.resumen is not null or new.contenido is not null
       or new.introduccion_html is not null or new.contenido_html is not null
       or new.versiculo is not null or new.imagen_url is not null
       or new.publicado is true or new.fecha_publicacion is not null
       or new.estado <> 'borrador' then
      raise exception 'Los artículos nuevos deben crearse mediante pending_content.' using errcode = '42501';
    end if;
    return new;
  end if;

  if new.titulo is distinct from old.titulo
     or new.resumen is distinct from old.resumen
     or new.contenido is distinct from old.contenido
     or new.introduccion_html is distinct from old.introduccion_html
     or new.contenido_html is distinct from old.contenido_html
     or new.versiculo is distinct from old.versiculo
     or new.categorias is distinct from old.categorias
     or new.autora is distinct from old.autora
     or new.imagen_url is distinct from old.imagen_url
     or new.publicado is distinct from old.publicado
     or new.fecha_publicacion is distinct from old.fecha_publicacion
     or new.estado is distinct from old.estado then
    raise exception 'No puedes modificar contenido publicado directamente; usa el flujo de revisión.' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists devocionales_guard_direct_writes on public.devocionales;
create trigger devocionales_guard_direct_writes
before insert or update on public.devocionales
for each row execute function public.devocionales_guard_direct_writes();

-- 4. Trigger de bitácora automática (creado/editado) ----------------------
create or replace function public.devocionales_log_activity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if TG_OP = 'INSERT' then
    insert into public.devocional_historial (devocional_id, devocional_titulo, devocional_slug, actor_id, actor_email, accion)
    values (new.id, coalesce(new.titulo, new.pending_content->>'titulo'), new.slug, auth.uid(),
      (select email from public.user_roles where user_id = auth.uid()), 'creado');
    return new;
  end if;

  if current_setting('app.devocional_guard_bypass', true) = 'on' then
    return new; -- la función que hizo el cambio ya registró su propia acción
  end if;

  if new.pending_content is distinct from old.pending_content
     or new.pending_fecha_publicacion is distinct from old.pending_fecha_publicacion then
    insert into public.devocional_historial (devocional_id, devocional_titulo, devocional_slug, actor_id, actor_email, accion)
    values (new.id, coalesce(new.titulo, new.pending_content->>'titulo'), new.slug, auth.uid(),
      (select email from public.user_roles where user_id = auth.uid()), 'editado');
  end if;
  return new;
end;
$$;

drop trigger if exists devocionales_log_activity on public.devocionales;
create trigger devocionales_log_activity
after insert or update on public.devocionales
for each row execute function public.devocionales_log_activity();

-- 5. Trigger de bitácora de borrado ----------------------------------------
create or replace function public.devocionales_log_delete()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.devocional_historial (devocional_id, devocional_titulo, devocional_slug, actor_id, actor_email, accion)
  values (old.id, coalesce(old.titulo, old.pending_content->>'titulo'), old.slug, auth.uid(),
    (select email from public.user_roles where user_id = auth.uid()), 'eliminado');
  return old;
end;
$$;

drop trigger if exists devocionales_log_delete on public.devocionales;
create trigger devocionales_log_delete
before delete on public.devocionales
for each row execute function public.devocionales_log_delete();

-- 6. Funciones de transición (una por acción bien definida) ----------------
create or replace function public.devocional_submit_for_review(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.devocionales%rowtype;
begin
  select * into target from public.devocionales where id = p_id for update;
  if not found then raise exception 'Devocional no encontrado.'; end if;
  if target.created_by <> auth.uid() or not public.has_permission('editor') then
    raise exception 'No tienes permiso para enviar este devocional a revisión.' using errcode = '42501';
  end if;
  if target.estado not in ('borrador', 'cambios_solicitados') then
    raise exception 'Este devocional ya está en revisión.';
  end if;
  if target.pending_content is null
     or coalesce(btrim(target.pending_content->>'titulo'), '') = ''
     or coalesce(btrim(target.pending_content->>'contenido'), '') = '' then
    raise exception 'Completa al menos el título y la reflexión antes de enviar a revisión.';
  end if;

  perform set_config('app.devocional_guard_bypass', 'on', true);
  update public.devocionales set estado = 'en_revision', updated_at = now() where id = p_id;

  insert into public.devocional_historial (devocional_id, devocional_titulo, devocional_slug, actor_id, actor_email, accion)
  values (p_id, coalesce(target.titulo, target.pending_content->>'titulo'), target.slug, auth.uid(),
    (select email from public.user_roles where user_id = auth.uid()), 'enviado_a_revision');
end;
$$;

revoke all on function public.devocional_submit_for_review(bigint) from public;
grant execute on function public.devocional_submit_for_review(bigint) to authenticated;

create or replace function public.devocional_request_changes(p_id bigint, p_nota text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.devocionales%rowtype;
  nota text := btrim(coalesce(p_nota, ''));
begin
  if nota = '' then raise exception 'Escribe una nota explicando los cambios solicitados.'; end if;
  select * into target from public.devocionales where id = p_id for update;
  if not found then raise exception 'Devocional no encontrado.'; end if;
  if target.created_by = auth.uid() or not public.has_permission('reviewer') then
    raise exception 'No tienes permiso para revisar este devocional.' using errcode = '42501';
  end if;
  if target.estado <> 'en_revision' then raise exception 'Este devocional no está en revisión.'; end if;

  perform set_config('app.devocional_guard_bypass', 'on', true);
  update public.devocionales set estado = 'cambios_solicitados', updated_at = now() where id = p_id;

  insert into public.devocional_historial (devocional_id, devocional_titulo, devocional_slug, actor_id, actor_email, accion, nota)
  values (p_id, coalesce(target.titulo, target.pending_content->>'titulo'), target.slug, auth.uid(),
    (select email from public.user_roles where user_id = auth.uid()), 'cambios_solicitados', nota);
end;
$$;

revoke all on function public.devocional_request_changes(bigint, text) from public;
grant execute on function public.devocional_request_changes(bigint, text) to authenticated;

create or replace function public.devocional_approve_and_publish(p_id bigint, p_fecha timestamptz default null)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.devocionales%rowtype;
  fecha timestamptz;
begin
  select * into target from public.devocionales where id = p_id for update;
  if not found then raise exception 'Devocional no encontrado.'; end if;
  if not (public.is_super_admin() or (public.has_permission('reviewer') and target.created_by <> auth.uid())) then
    raise exception 'No tienes permiso para aprobar este devocional.' using errcode = '42501';
  end if;
  if target.estado <> 'en_revision' then raise exception 'Este devocional no está en revisión.'; end if;
  if target.pending_content is null then raise exception 'No hay contenido pendiente para aprobar.'; end if;

  fecha := coalesce(p_fecha, target.pending_fecha_publicacion, now());

  perform set_config('app.devocional_guard_bypass', 'on', true);
  update public.devocionales set
    titulo = target.pending_content->>'titulo',
    resumen = target.pending_content->>'resumen',
    contenido = target.pending_content->>'contenido',
    contenido_html = target.pending_content->>'contenido_html',
    introduccion_html = target.pending_content->>'introduccion_html',
    versiculo = target.pending_content->>'versiculo',
    categorias = coalesce((select array_agg(value) from jsonb_array_elements_text(target.pending_content->'categorias')), '{}'),
    autora = coalesce(nullif(target.pending_content->>'autora', ''), target.autora),
    imagen_url = target.pending_content->>'imagen_url',
    publicado = true,
    fecha_publicacion = fecha,
    pending_content = null,
    pending_fecha_publicacion = null,
    estado = 'borrador',
    updated_at = now()
  where id = p_id;

  insert into public.devocional_historial (devocional_id, devocional_titulo, devocional_slug, actor_id, actor_email, accion)
  values (p_id, target.pending_content->>'titulo', target.slug, auth.uid(),
    (select email from public.user_roles where user_id = auth.uid()), 'aprobado_publicado');
end;
$$;

revoke all on function public.devocional_approve_and_publish(bigint, timestamptz) from public;
grant execute on function public.devocional_approve_and_publish(bigint, timestamptz) to authenticated;

create or replace function public.devocional_withdraw(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.devocionales%rowtype;
begin
  select * into target from public.devocionales where id = p_id for update;
  if not found then raise exception 'Devocional no encontrado.'; end if;
  if not (
    public.is_super_admin()
    or (public.has_permission('editor') and target.created_by = auth.uid())
    or (public.has_permission('reviewer') and target.created_by <> auth.uid())
  ) then
    raise exception 'No tienes permiso para retirar este devocional de revisión.' using errcode = '42501';
  end if;
  if target.estado <> 'en_revision' then raise exception 'Este devocional no está en revisión.'; end if;

  perform set_config('app.devocional_guard_bypass', 'on', true);
  update public.devocionales set estado = 'borrador', updated_at = now() where id = p_id;

  insert into public.devocional_historial (devocional_id, devocional_titulo, devocional_slug, actor_id, actor_email, accion)
  values (p_id, coalesce(target.titulo, target.pending_content->>'titulo'), target.slug, auth.uid(),
    (select email from public.user_roles where user_id = auth.uid()), 'retirado');
end;
$$;

revoke all on function public.devocional_withdraw(bigint) from public;
grant execute on function public.devocional_withdraw(bigint) to authenticated;

create or replace function public.devocional_unpublish(p_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.devocionales%rowtype;
begin
  select * into target from public.devocionales where id = p_id for update;
  if not found then raise exception 'Devocional no encontrado.'; end if;
  if not public.is_super_admin() then
    raise exception 'Solo el Super Admin puede retirar un devocional publicado.' using errcode = '42501';
  end if;
  if not target.publicado then raise exception 'Este devocional no está publicado.'; end if;

  perform set_config('app.devocional_guard_bypass', 'on', true);
  update public.devocionales set publicado = false, fecha_publicacion = null, updated_at = now() where id = p_id;

  insert into public.devocional_historial (devocional_id, devocional_titulo, devocional_slug, actor_id, actor_email, accion)
  values (p_id, target.titulo, target.slug, auth.uid(),
    (select email from public.user_roles where user_id = auth.uid()), 'despublicado');
end;
$$;

revoke all on function public.devocional_unpublish(bigint) from public;
grant execute on function public.devocional_unpublish(bigint) to authenticated;

-- 7. RLS: escritura ordinaria de devocionales (ahora Editor + Reviewer) ---
drop policy if exists "editors update own devocionales" on public.devocionales;
create policy "editors update own devocionales"
on public.devocionales for update to authenticated
using (public.has_permission('editor') and created_by = auth.uid())
with check (public.has_permission('editor') and created_by = auth.uid());

drop policy if exists "reviewers update queue devocionales" on public.devocionales;
create policy "reviewers update queue devocionales"
on public.devocionales for update to authenticated
using (
  public.has_permission('reviewer') and created_by <> auth.uid()
  and (estado in ('en_revision','cambios_solicitados') or publicado = true)
)
with check (public.has_permission('reviewer') and created_by <> auth.uid());

drop policy if exists "reviewers read queue devocionales" on public.devocionales;
create policy "reviewers read queue devocionales"
on public.devocionales for select to authenticated
using (
  public.has_permission('reviewer') and created_by <> auth.uid()
  and (estado in ('en_revision','cambios_solicitados') or publicado = true)
);

drop policy if exists "editors delete own devocionales" on public.devocionales;
create policy "editors delete own devocionales"
on public.devocionales for delete to authenticated
using (public.has_permission('editor') and created_by = auth.uid() and publicado = false);

-- storage.objects: reviewers también pueden subir portadas al editar directo.
drop policy if exists "editors upload devotional images" on storage.objects;
create policy "editorial upload devotional images"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'mcp930-images'
  and (public.has_permission('editor') or public.has_permission('reviewer'))
  and (storage.foldername(name))[1] = 'devocionales'
);
